(function($) {
    "use strict";
    $(function() {

        var simple_news_ticker_title_width = $('.simple-news-ticker-title').width(),
            simple_news_ticker_nav_widh = $('.simple-news-ticker-direction-nav').width(),
            simple_news_ticker_slider_width = simple_news_ticker_title_width + simple_news_ticker_slider_width;


        $(document).ready(function() {
            $('ul.simple-news-ticker').css({
                'width': simple_news_ticker_slider_width
            });
        });

        $(window).load(function() {
            var mmslide = $('.simple-news-ticker-wrapper');


            mmslide.flexslider({
                controlNav: false,
                animationLoop: true,
                slideshow: true,
                selector: 'ul.simple-news-ticker > li',
                directionNav: false,
                animation: 'fade',
                namespace: "simple-news-ticker-" //{NEW} String: Prefix string attached to the class of every element generated by the plugin

            }).show();



        });

        $('a.simple-news-ticker-next').click(function() {
            $('.simple-news-ticker-wrapper').flexslider("next"); //Go to next slide
        });

        $('a.simple-news-ticker-prev').click(function() {
            $('.simple-news-ticker-wrapper').flexslider("prev"); //Go to next slide
        });





    });
}(jQuery));
